version: '1.0.0'
services:
  app-backend-to-do-1:
    build: .
    image: to-do-backend-cc-proyect:1.0.0
    restart: always
    ports:
      - 3000:3000
    environment:
      INSTANCE: 1
      PORT: 3000
  app-backend-to-do-2:
    build: .
    image: to-do-backend-cc-proyect:1.0.0
    restart: always
    ports:
      - 3001:3001
    environment:
      INSTANCE: 2
      PORT: 3001
  balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app-backend-to-do-1
      - app-backend-to-do-2
